title:             Hello Geek 
email:             geek1250@gmail.com
description:       A Blog by a Geek
author:            HelloGeek.org
baseurl:           "/"
url:               ""

# Social Profiles
twitter_username:  
github_username:   
facebook_username: 

permalink: /blog/:categories/:title

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
